---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: vault
  namespace: vault
spec:
  ref:
    tag: 0.1.9
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  values:
    # additionalEnv:
    #   - name: OIDC_CLIENT_SECRET
    #     valueFrom:
    #       secretKeyRef:
    #         name: keycloak-vault-oauth-key
    #         key: key
    vault:
      volumes:
        - name: ingress-tls
          secret:
            defaultMode: 420
            secretName: vault.kind
      volumeMounts:
        - name: ingress-tls
          mountPath: /etc/ingress-tls
        - name: vault-raft
          mountPath: /vault/file
      config:
        telemetry:
          disable_hostname: true
          prometheus_retention_time: 24h
        storage:
          raft:
            path: "/vault/file"
        listener:
        - tcp:
            address: '[::]:8300'
            tls_cert_file: /etc/ingress-tls/tls.crt
            tls_key_file: /etc/ingress-tls/tls.key
        - tcp:
            address: '[::]:8200'
            telemetry:
              unauthenticated_metrics_access: true
            tls_cert_file: /vault/tls/server.crt
            tls_key_file: /vault/tls/server.key
        api_addr: https://vault:8200
        cluster_addr: "https://${.Env.POD_NAME}:8201"
        disable_mlock: true
        ui: true
      service:
        ports:
          api-port: 8200
          cluster-port: 8201
          ext-api-port: 8300
          ext-clu-port: 8301
      alertRules: 
        enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: prometheus
      serviceRegistration: true
      ingress:
        enabled: true
        className: "cilium"
        annotations: 
          cert-manager.io/cluster-issuer: vault-ca-issuer
          ingress.cilium.io/tls-passthrough: enabled 
        port: "8300"
        hosts:
          - host: vault.kind
            paths:
              - path: /
                pathType: Prefix
        tls:
        - hosts:
          - vault.kind
          secretName: vault.kind
      podSpec:
        # hostAliases:
        # - ip: "172.18.0.8"
        #   hostnames:
        #   - "keycloak.localhost"
        # - ip: "172.18.0.7"
        #   hostnames:
        #   - "keycloak.localhost"
        # - ip: "172.18.0.6"
        #   hostnames:
        #   - "keycloak.localhost"
        # - ip: "172.18.0.5"
        #   hostnames:
        #   - "keycloak.localhost"
        # - ip: "172.18.0.8"
        #   hostnames:
        #   - "gitlab.kind"
        # - ip: "172.18.0.7"
        #   hostnames:
        #   - "gitlab.kind"
        # - ip: "172.18.0.6"
        #   hostnames:
        #   - "gitlab.kind"
        # - ip: "172.18.0.5"
        #   hostnames:
        #   - "gitlab.kind"
      externalConfig:
        policies:
          - name: allow_kubernetes_namespaced_secrets
            rules: |
              path "kubernetes/data/{{identity.entity.aliases.${ accessor `kubernetes/` }.metadata.service_account_namespace}}/*" {
                capabilities = ["create", "read", "update", "delete", "list"]
              }
          - name: allow_shared_secrets
            rules: |
              path "shared/*" {
                capabilities = ["create", "read", "update", "delete", "list"]
              }
          - name: allow_admin
            rules: |
              path "*" {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }
          - name: allow_viewer
            rules: |
              path "*" {
                capabilities = ["read", "update", "list"]
              }
          - name: allow_configurer
            rules: |
              path "/sys/policies/*" {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "/sys/policy/*" {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "/identity/*" {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "auth/token/create" {
                capabilities = ["create", "update", "sudo"]
              }
          - name: allow_metrics
            rules: |
              path "/sys/metrics" {
                capabilities = ["read"]
              }
          - name: allow_backups
            rules: |
              path "/sys/storage/raft/snapshot" {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }
              path "/sys/storage/raft/snapshot-force" {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }
        auth:
          # - type: jwt
          #   path: jwt
          #   config:
          #     oidc_discovery_url: https://gitlab.kind
          #     bound_issuer: https://gitlab.kind
          #   roles:
          #   - name: default
          #     role_type: jwt
          #     bound_audiences:
          #       - https://vault.kind
          #     user_claim: user_email
          #     policies: allow_shared_secrets
          #     token_explicit_max_ttl: 60
          #     bound_claims_type: "glob"
          #     bound_claims: {
          #       "project_id": "*",
          #       "ref": "*"
          #     }
          - type: kubernetes
            roles:
              # Allow every pod in the default namespace to use the secret kv store
              - name: default
                bound_service_account_names: ["default"]
                bound_service_account_namespaces: ["*"]
                policies: ["allow_shared_secrets", "allow_namespaced_secrets"]
                ttl: 1h
              - name: monitoring
                bound_service_account_names: ["default"]
                bound_service_account_namespaces: ["*"]
                policies: ["allow_metrics"]
                ttl: 1h
              - name: backup
                bound_service_account_names: ["vault"]
                bound_service_account_namespaces: ["vault"]
                policies: ["allow_backups"]
                ttl: 1h
          # - type: oidc
          #   config:
          #     oidc_discovery_url: "http://keycloak.localhost/realms/realm01"
          #     oidc_client_id: vault-oauth
          #     oidc_client_secret: "${ env `OIDC_CLIENT_SECRET` }"
          #     default_role: default
          #   roles:
          #     # Allow every pod in the default namespace to use the secret kv store
          #     - name: default
          #       allowed_redirect_uris: ["https://vault.kind/ui/vault/auth/oidc/oidc/callback","https://vault.kind/oidc/callback","https://vault.kind:/oidc/callback","https://vault.kind:443/oidc/callback","http://localhost:8250/oidc/callback"]
          #       bound_audiences: vault-oauth
          #       user_claim: preferred_username
          #       groups_claim: "groups"
          #     - name: admin
          #       allowed_redirect_uris: ["https://vault.kind/ui/vault/auth/oidc/oidc/callback","https://vault.kind/oidc/callback","https://vault.kind:/oidc/callback","https://vault.kind:443/oidc/callback","http://localhost:8250/oidc/callback"]
          #       bound_audiences: vault-oauth
          #       user_claim: preferred_username
          #       policies: allow_admin
          #       bound_claims:
          #         groups: 
          #           - admin
    bankVaults:
      serviceMonitor:
        enabled: true
        labels:
          release: prometheus
    configurer:
      alertRules: 
        enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: prometheus
    fluentd:
      enabled: false
    statsd:
      enabled: false
      serviceMonitor:
        enabled: false
        labels:
          release: prometheus
    velero:
      enabled: false
    backups:
      enabled: false
      cronjob: 
        schedule: "* * * * *" 
        backoffLimit: 3
        restartPolicy: OnFailure
      restic:
        secretRef: restic
        image:
          repository: restic/restic 
          tag: 0.18.0
