---
apiVersion: v1
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: 'true'
  name: tenant2-cloud-config
  namespace: tenant2
stringData:
  clouds.yaml: |-
    clouds:
      openstack:
        auth:
          auth_url: https://cloud.api.selcloud.ru/identity/v3
          username: admin
          password: n8?3HfGV
          project_name: 417168
          project_id: c08e12c6d3da49b0a2f63d4871335830
          user_domain_name: 417168
        region_name: ru-3
        interface: public
        identity_api_version: 3
