---
apiVersion: v1
stringData:
  cloudconf: |
    apiVersion: v1
    stringData:
      cloud.conf: |
        [Global]
        auth-url=https://cloud.api.selcloud.ru/identity/v3
        username="admin"
        password="n8?3HfGV"
        tenant-id="c08e12c6d3da49b0a2f63d4871335830"
        tenant-name="417168"
        domain-name="417168"
        region="ru-3"
    kind: Secret
    metadata:
      name: tenant2-cloudconf
      namespace: kube-system
kind: Secret
metadata:
  name: tenant2-cloudconf
  namespace: tenant2
type: addons.cluster.x-k8s.io/resource-set
