{
 "title": "Hashicorp Vault",
 "description": " Hashicorp Vault Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mountpoint",
    "label": "Mount Point:",
    "query": {
     "query": "label_values(vault_secret_kv_count{datacenter=\"$datacenter\"},mount_point)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "datacenter", "label": "datacenter", "query": { "query": "label_values(datacenter)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(vault_core_active{datacenter=\"$datacenter\", job=\"vault\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vault_core_active{datacenter=\"$datacenter\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_secret_kv_count{datacenter=\"$datacenter\"})",
     "legendFormat": "{{ mount_point }}"
    }
   ]
  },
  {
   "title": "Number of Identity Entities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_identity_num_entities{datacenter=\"$datacenter\"})"
    }
   ]
  },
  {
   "title": "Identity Entities Aliases by Method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(instance) (vault_identity_entity_alias_count{datacenter=\"$datacenter\"})",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(1 + vault_core_unsealed{datacenter=\"$datacenter\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of Leases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_expire_num_leases{datacenter=\"$datacenter\"})"
    }
   ]
  },
  { "title": "Path Info: $mountpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "mountpoint" },
  {
   "title": "Number of Operations in \"$mountpoint\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(increase(vault_route_create_${mountpoint}__count{datacenter=\"$datacenter\"}[5m]))",
     "legendFormat": "Create"
    },
    {
     "expr": "avg(increase(vault_route_delete_${mountpoint}__count{datacenter=\"$datacenter\"}[5m]))",
     "legendFormat": "Delete"
    },
    {
     "expr": "avg(increase(vault_route_read_${mountpoint}__count{datacenter=\"$datacenter\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(increase(vault_route_list_${mountpoint}__count{datacenter=\"$datacenter\"}[5m]))",
     "legendFormat": "List"
    }
   ]
  },
  {
   "title": "Time of Operations in \"$mountpoint\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(rate(vault_route_create_${mountpoint}__sum{datacenter=\"$datacenter\"}[1m]) / rate(vault_route_create_${mountpoint}__count{datacenter=\"$datacenter\"}[1m]) * 1000)",
     "legendFormat": "Create"
    },
    {
     "expr": "avg(rate(vault_route_delete_${mountpoint}__sum{datacenter=\"$datacenter\"}[1m]) / rate(vault_route_delete_${mountpoint}__count{datacenter=\"$datacenter\"}[1m]) * 1000)",
     "legendFormat": "Delete"
    },
    {
     "expr": "avg(rate(vault_route_read_${mountpoint}__sum{datacenter=\"$datacenter\"}[1m]) / rate(vault_route_read_${mountpoint}__count{datacenter=\"$datacenter\"}[1m]) * 1000)",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(rate(vault_route_list_${mountpoint}__sum{datacenter=\"$datacenter\"}[1m]) / rate(vault_route_list_${mountpoint}__count{datacenter=\"$datacenter\"}[1m]) * 1000)",
     "legendFormat": "List"
    }
   ]
  },
  { "title": "CPU/Mem Info: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }, "repeat": "instance" },
  {
   "title": "Heap Objects Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_heap_objects{datacenter=\"$datacenter\", instance=\"${instance}\"} / vault_runtime_malloc_count{datacenter=\"$datacenter\", instance=\"${instance}\"})"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_num_goroutines{datacenter=\"$datacenter\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Allocated MB",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(vault_runtime_alloc_bytes{datacenter=\"$datacenter\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available Tokens",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(vault_token_count{datacenter=\"$datacenter\"})"
      }
     ]
    },
    {
     "title": "Tokens by Policy",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_count_by_policy{datacenter=\"$datacenter\"})",
       "legendFormat": "{{ policy }}"
      }
     ]
    },
    {
     "title": "Pending Tokens",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_token_create_count - vault_token_store_count{datacenter=\"$datacenter\"})"
      }
     ]
    },
    {
     "title": "Tokens by TTL",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_count_by_ttl{datacenter=\"$datacenter\"})",
       "legendFormat": "{{ creation_ttl }}"
      }
     ]
    },
    {
     "title": "Tokens by Auth Method",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_count_by_auth{datacenter=\"$datacenter\"})",
       "legendFormat": "{{ auth_method }}"
      }
     ]
    },
    {
     "title": "Tokens Creation by Method & TTL",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(auth_method, creation_ttl) (vault_token_creation{datacenter=\"$datacenter\"})",
       "legendFormat": "{{ auth_method }} - {{ creation_ttl }}"
      }
     ]
    },
    {
     "title": "Token Creation/Storage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg without(instance) (vault_token_create_count{datacenter=\"$datacenter\"})",
       "legendFormat": "Create"
      },
      {
       "expr": "avg without(instance) (vault_token_store_count{datacenter=\"$datacenter\"})",
       "legendFormat": "Store"
      }
     ]
    },
    {
     "title": "Token Lookups",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vault_token_lookup_count{datacenter=\"$datacenter\"}[1m]))",
       "legendFormat": "Lookups"
      }
     ]
    }
   ]
  },
  {
   "title": "Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Request Failures",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 74 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(idelta(vault_audit_log_request_failure{datacenter=\"$datacenter\"}[1m]))",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "Log Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 3, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vault_audit_log_request_count{datacenter=\"$datacenter\"}[1m]))",
       "legendFormat": "Request "
      },
      {
       "expr": "avg(irate(vault_audit_log_response_count{datacenter=\"$datacenter\"}[1m]))",
       "legendFormat": "Response"
      },
      {
       "expr": "avg(irate(vault_core_handle_request_count{datacenter=\"$datacenter\"}[1m]))",
       "legendFormat": "Handled"
      }
     ]
    },
    {
     "title": "Consul Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vault_raft_storage_get_count{datacenter=\"$datacenter\"}[1m]))",
       "legendFormat": "GET"
      },
      {
       "expr": "avg(irate(vault_raft_storage_put_count{datacenter=\"$datacenter\"}[1m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(irate(vault_raft_storage_delete_count{datacenter=\"$datacenter\"}[1m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "irate(vault_raft_storage_list_count{datacenter=\"$datacenter\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Log Response Failures",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 79 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(idelta(vault_audit_log_response_failure{datacenter=\"$datacenter\"}[1m]))",
       "legendFormat": "Request"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Policy Set",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 202 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vault_policy_set_policy_count{datacenter=\"$datacenter\"}[1m]))",
       "legendFormat": "SET"
      }
     ]
    },
    {
     "title": "Policy Get",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 202 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vault_policy_get_policy_count{datacenter=\"$datacenter\"}[1m]))",
       "legendFormat": "GET"
      }
     ]
    }
   ]
  },
  {
   "title": "Vault config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vault configured",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "vault_config_successful{job=\"vault-configurer\",datacenter=\"$datacenter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vault config failed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "vault_config_failed{job=\"vault-configurer\",datacenter=\"$datacenter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vault seal status",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(vault_sys_sealed{datacenter=\"$datacenter\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vault init status",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(vault_sys_initialized{datacenter=\"$datacenter\"})/count(vault_sys_initialized{datacenter=\"$datacenter\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}