nameOverride: ""
fullnameOverride: ""
vault:
  size: 3
  image:
    repository: hashicorp/vault
    pullPolicy: IfNotPresent
    tag: "1.19.0"
  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""
  podAnnotations: {}
  annotations: {}
  podSecurityContext:
    fsGroup: 100
    runAsUser: 100
    runAsGroup: 100
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    runAsGroup: 100
    runAsNonRoot: true
    runAsUser: 100
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsUser: 100
    runAsGroup: 100
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - "ALL"
  service:
    type: ClusterIP
    ports: []
  serviceMonitor: 
    labels: {}
    enabled: false
  alertRules: 
    labels: {}
    enabled: false
  operatorServiceMonitor: false
  ingress:
    enabled: false
    port: 8200
    className: ""
    annotations: {}
    # hosts:
    #   - host: vault.localhost
    #     paths:
    #       - path: /
    #         pathType: Prefix
    # tls:
    # - hosts:
    #   - vault.localhost
    #   secretName: vault-tls
  resources:
    limits:
      memory: "512Mi"
      cpu: "200m"
    requests:
      memory: "256Mi"
      cpu: "100m"
  livenessProbe:
    httpGet:
      path: /v1/sys/health?standbyok=true
      port: api-port
    failureThreshold: 1
    periodSeconds: 60
    terminationGracePeriodSeconds: 60
  readinessProbe:
    httpGet:
      path: /v1/sys/health?standbyok=true
      port: api-port
    failureThreshold: 1
    periodSeconds: 60
  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
        # storageClassName: ""
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
  volumeMounts:
    - name: vault-raft
      mountPath: /vault/file
  nodeSelector: {}
  tolerations: []
  additionalEnv:
    - name: VAULT_LOG_LEVEL
      value: debug
    - name: SKIP_CHOWN
      value: "true"
    - name: SKIP_SETCAP
      value: "true"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: vault
          topologyKey: kubernetes.io/hostname
  tls:
    certManager:
      enabled: true
      createIssuer: true
      namespace: cert-manager

      issuerRef: {}
      secretsOperator:
        createCertificate: true
        namespace: vault-secrets-operator
    existingSecret: ""
  config:
    storage:
      raft:
        path: "/vault/file"
    listener:
      tcp:
        address: "[::]:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.default:8200
    cluster_addr: "https://${.Env.POD_NAME}:8201"
    disable_mlock: true
    ui: true
  externalConfig:
    policies:
      - name: allow_namespaced_secrets
        rules: |
          path "namespaces/data/{{identity.entity.aliases.${ accessor `kubernetes/` }.metadata.service_account_namespace}}/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: allow_shared_secrets
        rules: |
          path "shared/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: allow_backups
        rules: |
          path "/sys/storage/raft/snapshot" {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }
          path "/sys/storage/raft/snapshot-force" {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }
    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the default namespace to use the secret kv store
          - name: default
            bound_service_account_names: ["default"]
            bound_service_account_namespaces: ["*"]
            policies: ["allow_shared_secrets", "allow_namespaced_secrets"]
            ttl: 1h
          - name: monitoring
            bound_service_account_names: ["default"]
            bound_service_account_namespaces: ["*"]
            policies: ["allow_metrics"]
            ttl: 1h
          - name: backup
            bound_service_account_names: ["vault"]
            bound_service_account_namespaces: ["vault"]
            policies: ["allow_backups"]
            ttl: 1h
    secrets:
      - path: namespaces
        type: kv
        description: Kubernetes secrets.
        options:
          version: 2
      - path: shared
        type: kv
        description: Kubernetes shared secrets.
        options:
          version: 2
    startupSecrets:
      - type: kv
        path: namespaces/data/vso-example/helloworld
        data:
          data:
            username: testuser
            password: testpassword
configurer:
  serviceMonitor:
    labels: {}
    enabled: false
  alertRules: 
    labels: {}
    enabled: false
bankVaults:
  image:
    repository: ghcr.io/banzaicloud/bank-vaults
    pullPolicy: IfNotPresent
    tag: "1.19.0"
  resources:
    limits:
      memory: "512Mi"
      cpu: "200m"
    requests:
      memory: "256Mi"
      cpu: "100m"
  serviceMonitor:
    labels: {}
    enabled: false
fluentd:
  enabled: false
statsd:
  enabled: false
  serviceMonitor:
    labels: {}
    enabled: false
  image: 'prom/statsd-exporter:latest'
  resources: {}
  config:
    mappings:
      - match: vault.route.*.*
        name: "vault_route"
        labels:
          method: "$1"
          path: "$2"
velero:
  enabled: false
backups:
  enabled: false
  cronjob:
    schedule: "* * * * *"
    backoffLimit: 3
    restartPolicy: OnFailure
  restic:
    # Must contain RESTIC_PASSWORD RESTIC_REPOSITORY AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID
    secretRef: vault-restic
    image:
      repository: restic/restic
      tag: 0.18.0
hsmDaemon: {}
