{{- if .Values.vault.alertRules.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: {{ include "vault.fullname" . }}
  {{- with .Values.vault.alertRules.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "vault.fullname" . }}-backups
spec:
  groups:
  - name: vault-backups
    rules:
    - alert: VaultFailedJobs
      annotations:
        summary: Vault Jobs Failed
        description: "Vault namespace has failed jobs, probably backups "
        details: "{% raw %}cluster {{`{{`}} $labels.cluster {{`}}`}}{% endraw %}"
      expr: avg(kube_job_status_failed{namespace="{{ .Release.Namespace }}"}) > 0
      for: 1m
      labels:
        severity: warning
        responsible: cloudsre
        sort_by_value: ascending
        send_to_automata: "false"
        send_to_jira: "false"
        send_to_duty_chats: "false"
{{- end }}
