{{- if .Values.bankVaults.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: {{ include "vault.fullname" . }}-bank-vaults
  {{- with .Values.bankVaults.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "vault.fullname" . }}-bank-vaults
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
    scheme: http
    relabelings:
    - action: replace
      targetLabel: job
      replacement: bank-vaults
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
         - {{ include "vault.fullname" . }}
      - key: vault_cr
        operator: In
        values:
         - {{ include "vault.fullname" . }}
      - key: global_service
        operator: DoesNotExist
{{- end }}
